spring.application.name=habersitesi

# Veritabanı Bağlantısı
spring.datasource.url=jdbc:postgresql://localhost:5432/habersitesi
spring.datasource.username=postgres
spring.datasource.password=1234

# Otomatik Tablo Oluşturma
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Port Ayarı
server.port=8080

# --- Mail Gönderme Ayarları ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yusufzkrdz@gmail.com
# DIKKAT: Buraya Gmail sifresi degil, 16 haneli Uygulama sifresi yazılmalıdır.
spring.mail.password=mkfl emys bxbb zmia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
