spring.application.name=habersitesi

# Veritabanı Bağlantısı 
spring.datasource.url=postgresql://haberuser:0ecRYCmrBWvip6sn52olOIQBvmE18b8d@dpg-d7605iea2pns73flo3g0-a.frankfurt-postgres.render.com/haberdb_1t6z
spring.datasource.driver-class-name=org.postgresql.Driver

# Tabloyu Sıfırdan Kursun (Hata almamak için bir kereliğine CREATE yapıyoruz)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# --- Mail Gönderme Ayarları ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yusufzkrdz@gmail.com
spring.mail.password=mkfl emys bxbb zmia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
