spring.application.name=habersitesi

# Veritabanı Bağlantısı (Garanti Yol)
spring.datasource.url=jdbc:postgresql://dpg-cv4v6dl6l47c739m9s1g-a.oregon-postgres.render.com/habersitesi_7m3d?ssl=true
spring.datasource.username=habersitesi_7m3d_user
spring.datasource.password=T5S0F966mS0g9u6P6o6g6r6a6m6c6ı6
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Ayarları
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8080

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=yusufzkrdz@gmail.com
spring.mail.password=mkfl emys bxbb zmia
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
